# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.cache/wt [current_project]
set_property parent.project_path /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_quad_spi_flash_0/system_axi_quad_spi_flash_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_quad_spi_flash_0/system_axi_quad_spi_flash_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_quad_spi_flash_0/system_axi_quad_spi_flash_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_quad_spi_flash_0/system_axi_quad_spi_flash_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_0/system_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_0/system_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_0/system_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_clock_converter_0_1/system_axi_clock_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_clock_converter_0_1/system_axi_clock_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_clock_converter_0_1/system_axi_clock_converter_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph_0/system_axi_cc_periph_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph_0/system_axi_cc_periph_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph_0/system_axi_cc_periph_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph1_0/system_axi_cc_periph1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph1_0/system_axi_cc_periph1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_cc_periph1_0/system_axi_cc_periph1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_main_rst_0/system_main_rst_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_main_rst_0/system_main_rst_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_main_rst_0/system_main_rst_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ddr_int_rst_0/system_ddr_int_rst_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ddr_int_rst_0/system_ddr_int_rst_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_ddr_int_rst_0/system_ddr_int_rst_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_late.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_clk_wiz_1_1/system_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_ethernetlite_0_1/system_axi_ethernetlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_ethernetlite_0_1/system_axi_ethernetlite_0_1.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_ethernetlite_0_1/system_axi_ethernetlite_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_axi_ethernetlite_0_1/system_axi_ethernetlite_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_7/system_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_7/system_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_7/system_auto_cc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_6/system_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_6/system_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_6/system_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_5/system_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_5/system_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_5/system_auto_cc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_4/system_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_4/system_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_4/system_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_3/system_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_3/system_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_3/system_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_8/system_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_8/system_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_8/system_auto_cc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_m00_data_fifo_0/system_m00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/constrs_1/imports/digilent-xdc/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.srcs/constrs_1/imports/digilent-xdc/Arty-A7-35-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
