webtalk_init -webtalk_dir /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-09-17 10:42:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2hj0setcu8nd6qdg34p1eqfqt9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_21" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3826.992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33,000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1537129415000" -context "sdk\\\\bsp/1537129415000"
webtalk_add_data -client sdk -key hwid -value "1530997723000" -context "sdk\\\\bsp/1537129415000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1537129415000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1537129415000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1537129415000"
webtalk_add_data -client sdk -key uid -value "1537129416000" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key hwid -value "1530997723000" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key bspid -value "1537129415000" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key projSize -value "95.625" -context "sdk\\\\application/1537129416000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1537170123824"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1537170123824"
webtalk_transmit -clientid 3114464651 -regid "" -xml /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/constantine/Work/ARTY_A7/Vivado_prjct_final/Vivado_prjct.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
